name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create dummy HOWM_DIR for testing
      run: |
        mkdir -p /tmp/howm-test
        echo "dummy howm content" > /tmp/howm-test/dummy.howm

    - name: Create Makefile.local for CI
      run: |
        echo 'HOWM_DIR = /tmp/howm-test' > Makefile.local

    - name: Build dev container image
      run: make build-dev

    - name: Run tests on docker container
      run: make test
